version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: custom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shivohini
    ports:
      - "5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always

  backend:
    build: ./backend
    container_name: custom_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/shivohini
    depends_on:
      - postgres
    restart: always

  frontend:
    build: ./frontend
    container_name: custom_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
